AllCops:
  Exclude:
    - ".bundle/**/*"
    - "vendor/**/*"

LineLength:
  Max: 80
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"  # Arrays use brackets

SingleSpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

inherit_from: test/rubocop/enabled.yml
inherit_from: test/rubocop/disabled.yml
